<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::table('countries')->delete();

		$countries = array(
			array('name' => 'AFGHANISTAN', 'iso' => 'AF', 'iso3' => 'AFG', 'numcode' => '4', 'phonecode' => '93', 'currency' => ''),
            array('name' => 'ALBANIA', 'iso' => 'AL', 'iso3' => 'ALB', 'numcode' => '8', 'phonecode' => '355', 'currency' => ''),
            array('name' => 'ALGERIA', 'iso' => 'DZ', 'iso3' => 'DZA', 'numcode' => '12', 'phonecode' => '213', 'currency' => ''),
            array('name' => 'AMERICAN SAMOA', 'iso' => 'AS', 'iso3' => 'ASM', 'numcode' => '16', 'phonecode' => '1684', 'currency' => ''),
            array('name' => 'ANDORRA', 'iso' => 'AD', 'iso3' => 'AND', 'numcode' => '20', 'phonecode' => '376', 'currency' => ''),
            array('name' => 'ANGOLA', 'iso' => 'AO', 'iso3' => 'AGO', 'numcode' => '24', 'phonecode' => '244', 'currency' => ''),
            array('name' => 'ANGUILLA', 'iso' => 'AI', 'iso3' => 'AIA', 'numcode' => '660', 'phonecode' => '1264', 'currency' => ''),
            array('name' => 'ANTARCTICA', 'iso' => 'AQ', 'iso3' => 'ATA', 'numcode' => '', 'phonecode' => '0', 'currency' => ''),
            array('name' => 'ANTIGUA AND BARBUDA', 'iso' => 'AG', 'iso3' => 'ATG', 'numcode' => '28', 'phonecode' => '1268', 'currency' => ''),
            array('name' => 'ARGENTINA', 'iso' => 'AR', 'iso3' => 'ARG', 'numcode' => '32', 'phonecode' => '54', 'currency' => ''),
            array('name' => 'ARMENIA', 'iso' => 'AM', 'iso3' => 'ARM', 'numcode' => '51', 'phonecode' => '374', 'currency' => ''),
            array('name' => 'ARUBA', 'iso' => 'AW', 'iso3' => 'ABW', 'numcode' => '533', 'phonecode' => '297', 'currency' => ''),
            array('name' => 'AUSTRALIA', 'iso' => 'AU', 'iso3' => 'AUS', 'numcode' => '36', 'phonecode' => '61', 'currency' => ''),
            array('name' => 'AUSTRIA', 'iso' => 'AT', 'iso3' => 'AUT', 'numcode' => '40', 'phonecode' => '43', 'currency' => ''),
            array('name' => 'AZERBAIJAN', 'iso' => 'AZ', 'iso3' => 'AZE', 'numcode' => '31', 'phonecode' => '994', 'currency' => ''),
            array('name' => 'BAHAMAS', 'iso' => 'BS', 'iso3' => 'BHS', 'numcode' => '44', 'phonecode' => '1242', 'currency' => ''),
            array('name' => 'BAHRAIN', 'iso' => 'BH', 'iso3' => 'BHR', 'numcode' => '48', 'phonecode' => '973', 'currency' => ''),
            array('name' => 'BANGLADESH', 'iso' => 'BD', 'iso3' => 'BGD', 'numcode' => '50', 'phonecode' => '880', 'currency' => ''),
            array('name' => 'BARBADOS', 'iso' => 'BB', 'iso3' => 'BRB', 'numcode' => '52', 'phonecode' => '1246', 'currency' => ''),
            array('name' => 'BELARUS', 'iso' => 'BY', 'iso3' => 'BLR', 'numcode' => '112', 'phonecode' => '375', 'currency' => ''),
            array('name' => 'BELGIUM', 'iso' => 'BE', 'iso3' => 'BEL', 'numcode' => '56', 'phonecode' => '32', 'currency' => ''),
            array('name' => 'BELIZE', 'iso' => 'BZ', 'iso3' => 'BLZ', 'numcode' => '84', 'phonecode' => '501', 'currency' => ''),
            array('name' => 'BENIN', 'iso' => 'BJ', 'iso3' => 'BEN', 'numcode' => '204', 'phonecode' => '229', 'currency' => ''),
            array('name' => 'BERMUDA', 'iso' => 'BM', 'iso3' => 'BMU', 'numcode' => '60', 'phonecode' => '1441', 'currency' => ''),
            array('name' => 'BHUTAN', 'iso' => 'BT', 'iso3' => 'BTN', 'numcode' => '64', 'phonecode' => '975', 'currency' => ''),
            array('name' => 'BOLIVIA', 'iso' => 'BO', 'iso3' => 'BOL', 'numcode' => '68', 'phonecode' => '591', 'currency' => ''),
            array('name' => 'BOSNIA AND HERZEGOVINA', 'iso' => 'BA', 'iso3' => 'BIH', 'numcode' => '70', 'phonecode' => '387', 'currency' => ''),
            array('name' => 'BOTSWANA', 'iso' => 'BW', 'iso3' => 'BWA', 'numcode' => '72', 'phonecode' => '267', 'currency' => ''),
            array('name' => 'BOUVET ISLAND', 'iso' => 'BV', 'iso3' => 'BVT', 'numcode' => '', 'phonecode' => '0', 'currency' => ''),
            array('name' => 'BRAZIL', 'iso' => 'BR', 'iso3' => 'BRA', 'numcode' => '76', 'phonecode' => '55', 'currency' => ''),
            array('name' => 'BRITISH INDIAN OCEAN TERRITORY', 'iso' => 'IO', 'iso3' => 'IOT', 'numcode' => '', 'phonecode' => '246', 'currency' => ''),
            array('name' => 'BRUNEI DARUSSALAM', 'iso' => 'BN', 'iso3' => 'BRN', 'numcode' => '96', 'phonecode' => '673', 'currency' => ''),
            array('name' => 'BULGARIA', 'iso' => 'BG', 'iso3' => 'BGR', 'numcode' => '100', 'phonecode' => '359', 'currency' => ''),
            array('name' => 'BURKINA FASO', 'iso' => 'BF', 'iso3' => 'BFA', 'numcode' => '854', 'phonecode' => '226', 'currency' => ''),
            array('name' => 'BURUNDI', 'iso' => 'BI', 'iso3' => 'BDI', 'numcode' => '108', 'phonecode' => '257', 'currency' => ''),
            array('name' => 'CAMBODIA', 'iso' => 'KH', 'iso3' => 'KHM', 'numcode' => '116', 'phonecode' => '855', 'currency' => ''),
            array('name' => 'CAMEROON', 'iso' => 'CM', 'iso3' => 'CMR', 'numcode' => '120', 'phonecode' => '237', 'currency' => ''),
            array('name' => 'CANADA', 'iso' => 'CA', 'iso3' => 'CAN', 'numcode' => '124', 'phonecode' => '1', 'currency' => ''),
            array('name' => 'CAPE VERDE', 'iso' => 'CV', 'iso3' => 'CPV', 'numcode' => '132', 'phonecode' => '238', 'currency' => ''),
            array('name' => 'CAYMAN ISLANDS', 'iso' => 'KY', 'iso3' => 'CYM', 'numcode' => '136', 'phonecode' => '1345', 'currency' => ''),
            array('name' => 'CENTRAL AFRICAN REPUBLIC', 'iso' => 'CF', 'iso3' => 'CAF', 'numcode' => '140', 'phonecode' => '236', 'currency' => ''),
            array('name' => 'CHAD', 'iso' => 'TD', 'iso3' => 'TCD', 'numcode' => '148', 'phonecode' => '235', 'currency' => ''),
            array('name' => 'CHILE', 'iso' => 'CL', 'iso3' => 'CHL', 'numcode' => '152', 'phonecode' => '56', 'currency' => ''),
            array('name' => 'CHINA', 'iso' => 'CN', 'iso3' => 'CHN', 'numcode' => '156', 'phonecode' => '86', 'currency' => ''),
            array('name' => 'CHRISTMAS ISLAND', 'iso' => 'CX', 'iso3' => 'CXR', 'numcode' => '', 'phonecode' => '61', 'currency' => ''),
            array('name' => 'COCOS (KEELING) ISLANDS', 'iso' => 'CC', 'iso3' => 'CCK', 'numcode' => '', 'phonecode' => '672', 'currency' => ''),
            array('name' => 'COLOMBIA', 'iso' => 'CO', 'iso3' => 'COL', 'numcode' => '170', 'phonecode' => '57', 'currency' => ''),
            array('name' => 'COMOROS', 'iso' => 'KM', 'iso3' => 'COM', 'numcode' => '174', 'phonecode' => '269', 'currency' => ''),
            array('name' => 'CONGO', 'iso' => 'CG', 'iso3' => 'COG', 'numcode' => '178', 'phonecode' => '242', 'currency' => ''),
            array('name' => 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'iso' => 'CD', 'iso3' => 'COD', 'numcode' => '180', 'phonecode' => '242', 'currency' => ''),
            array('name' => 'COOK ISLANDS', 'iso' => 'CK', 'iso3' => 'COK', 'numcode' => '184', 'phonecode' => '682', 'currency' => ''),
            array('name' => 'COSTA RICA', 'iso' => 'CR', 'iso3' => 'CRI', 'numcode' => '188', 'phonecode' => '506', 'currency' => ''),
            array('name' => 'COTE D\'IVOIRE', 'iso' => 'CI', 'iso3' => 'CIV', 'numcode' => '384', 'phonecode' => '225', 'currency' => ''),
            array('name' => 'CROATIA', 'iso' => 'HR', 'iso3' => 'HRV', 'numcode' => '191', 'phonecode' => '385', 'currency' => ''),
            array('name' => 'CUBA', 'iso' => 'CU', 'iso3' => 'CUB', 'numcode' => '192', 'phonecode' => '53', 'currency' => ''),
            array('name' => 'CYPRUS', 'iso' => 'CY', 'iso3' => 'CYP', 'numcode' => '196', 'phonecode' => '357', 'currency' => ''),
            array('name' => 'CZECH REPUBLIC', 'iso' => 'CZ', 'iso3' => 'CZE', 'numcode' => '203', 'phonecode' => '420', 'currency' => ''),
            array('name' => 'DENMARK', 'iso' => 'DK', 'iso3' => 'DNK', 'numcode' => '208', 'phonecode' => '45', 'currency' => ''),
            array('name' => 'DJIBOUTI', 'iso' => 'DJ', 'iso3' => 'DJI', 'numcode' => '262', 'phonecode' => '253', 'currency' => ''),
            array('name' => 'DOMINICA', 'iso' => 'DM', 'iso3' => 'DMA', 'numcode' => '212', 'phonecode' => '1767', 'currency' => ''),
            array('name' => 'DOMINICAN REPUBLIC', 'iso' => 'DO', 'iso3' => 'DOM', 'numcode' => '214', 'phonecode' => '1809', 'currency' => ''),
            array('name' => 'ECUADOR', 'iso' => 'EC', 'iso3' => 'ECU', 'numcode' => '218', 'phonecode' => '593', 'currency' => ''),
            array('name' => 'EGYPT', 'iso' => 'EG', 'iso3' => 'EGY', 'numcode' => '818', 'phonecode' => '20', 'currency' => ''),
            array('name' => 'EL SALVADOR', 'iso' => 'SV', 'iso3' => 'SLV', 'numcode' => '222', 'phonecode' => '503', 'currency' => ''),
            array('name' => 'EQUATORIAL GUINEA', 'iso' => 'GQ', 'iso3' => 'GNQ', 'numcode' => '226', 'phonecode' => '240', 'currency' => ''),
            array('name' => 'ERITREA', 'iso' => 'ER', 'iso3' => 'ERI', 'numcode' => '232', 'phonecode' => '291', 'currency' => ''),
            array('name' => 'ESTONIA', 'iso' => 'EE', 'iso3' => 'EST', 'numcode' => '233', 'phonecode' => '372', 'currency' => ''),
            array('name' => 'ETHIOPIA', 'iso' => 'ET', 'iso3' => 'ETH', 'numcode' => '231', 'phonecode' => '251', 'currency' => ''),
            array('name' => 'FALKLAND ISLANDS (MALVINAS)', 'iso' => 'FK', 'iso3' => 'FLK', 'numcode' => '238', 'phonecode' => '500', 'currency' => ''),
            array('name' => 'FAROE ISLANDS', 'iso' => 'FO', 'iso3' => 'FRO', 'numcode' => '234', 'phonecode' => '298', 'currency' => ''),
            array('name' => 'FIJI', 'iso' => 'FJ', 'iso3' => 'FJI', 'numcode' => '242', 'phonecode' => '679', 'currency' => ''),
            array('name' => 'FINLAND', 'iso' => 'FI', 'iso3' => 'FIN', 'numcode' => '246', 'phonecode' => '358', 'currency' => ''),
            array('name' => 'FRANCE', 'iso' => 'FR', 'iso3' => 'FRA', 'numcode' => '250', 'phonecode' => '33', 'currency' => ''),
            array('name' => 'FRENCH GUIANA', 'iso' => 'GF', 'iso3' => 'GUF', 'numcode' => '254', 'phonecode' => '594', 'currency' => ''),
            array('name' => 'FRENCH POLYNESIA', 'iso' => 'PF', 'iso3' => 'PYF', 'numcode' => '258', 'phonecode' => '689', 'currency' => ''),
            array('name' => 'FRENCH SOUTHERN TERRITORIES', 'iso' => 'TF', 'iso3' => 'ATF', 'numcode' => '', 'phonecode' => '0', 'currency' => ''),
            array('name' => 'GABON', 'iso' => 'GA', 'iso3' => 'GAB', 'numcode' => '266', 'phonecode' => '241', 'currency' => ''),
            array('name' => 'GAMBIA', 'iso' => 'GM', 'iso3' => 'GMB', 'numcode' => '270', 'phonecode' => '220', 'currency' => ''),
            array('name' => 'GEORGIA', 'iso' => 'GE', 'iso3' => 'GEO', 'numcode' => '268', 'phonecode' => '995', 'currency' => ''),
            array('name' => 'GERMANY', 'iso' => 'DE', 'iso3' => 'DEU', 'numcode' => '276', 'phonecode' => '49', 'currency' => ''),
            array('name' => 'GHANA', 'iso' => 'GH', 'iso3' => 'GHA', 'numcode' => '288', 'phonecode' => '233', 'currency' => ''),
            array('name' => 'GIBRALTAR', 'iso' => 'GI', 'iso3' => 'GIB', 'numcode' => '292', 'phonecode' => '350', 'currency' => ''),
            array('name' => 'GREECE', 'iso' => 'GR', 'iso3' => 'GRC', 'numcode' => '300', 'phonecode' => '30', 'currency' => ''),
            array('name' => 'GREENLAND', 'iso' => 'GL', 'iso3' => 'GRL', 'numcode' => '304', 'phonecode' => '299', 'currency' => ''),
            array('name' => 'GRENADA', 'iso' => 'GD', 'iso3' => 'GRD', 'numcode' => '308', 'phonecode' => '1473', 'currency' => ''),
            array('name' => 'GUADELOUPE', 'iso' => 'GP', 'iso3' => 'GLP', 'numcode' => '312', 'phonecode' => '590', 'currency' => ''),
            array('name' => 'GUAM', 'iso' => 'GU', 'iso3' => 'GUM', 'numcode' => '316', 'phonecode' => '1671', 'currency' => ''),
            array('name' => 'GUATEMALA', 'iso' => 'GT', 'iso3' => 'GTM', 'numcode' => '320', 'phonecode' => '502', 'currency' => ''),
            array('name' => 'GUINEA', 'iso' => 'GN', 'iso3' => 'GIN', 'numcode' => '324', 'phonecode' => '224', 'currency' => ''),
            array('name' => 'GUINEA-BISSAU', 'iso' => 'GW', 'iso3' => 'GNB', 'numcode' => '624', 'phonecode' => '245', 'currency' => ''),
            array('name' => 'GUYANA', 'iso' => 'GY', 'iso3' => 'GUY', 'numcode' => '328', 'phonecode' => '592', 'currency' => ''),
            array('name' => 'HAITI', 'iso' => 'HT', 'iso3' => 'HTI', 'numcode' => '332', 'phonecode' => '509', 'currency' => ''),
            array('name' => 'HEARD ISLAND AND MCDONALD ISLANDS', 'iso' => 'HM', 'iso3' => 'HMD', 'numcode' => '', 'phonecode' => '0', 'currency' => ''),
            array('name' => 'HOLY SEE (VATICAN CITY STATE)', 'iso' => 'VA', 'iso3' => 'VAT', 'numcode' => '336', 'phonecode' => '39', 'currency' => ''),
            array('name' => 'HONDURAS', 'iso' => 'HN', 'iso3' => 'HND', 'numcode' => '340', 'phonecode' => '504', 'currency' => ''),
            array('name' => 'HONG KONG', 'iso' => 'HK', 'iso3' => 'HKG', 'numcode' => '344', 'phonecode' => '852', 'currency' => ''),
            array('name' => 'HUNGARY', 'iso' => 'HU', 'iso3' => 'HUN', 'numcode' => '348', 'phonecode' => '36', 'currency' => ''),
            array('name' => 'ICELAND', 'iso' => 'IS', 'iso3' => 'ISL', 'numcode' => '352', 'phonecode' => '354', 'currency' => ''),
            array('name' => 'INDIA', 'iso' => 'IN', 'iso3' => 'IND', 'numcode' => '356', 'phonecode' => '91', 'currency' => ''),
            array('name' => 'INDONESIA', 'iso' => 'ID', 'iso3' => 'IDN', 'numcode' => '360', 'phonecode' => '62', 'currency' => ''),
            array('name' => 'IRAN, ISLAMIC REPUBLIC OF', 'iso' => 'IR', 'iso3' => 'IRN', 'numcode' => '364', 'phonecode' => '98', 'currency' => ''),
            array('name' => 'IRAQ', 'iso' => 'IQ', 'iso3' => 'IRQ', 'numcode' => '368', 'phonecode' => '964', 'currency' => ''),
            array('name' => 'IRELAND', 'iso' => 'IE', 'iso3' => 'IRL', 'numcode' => '372', 'phonecode' => '353', 'currency' => ''),
            array('name' => 'ISRAEL', 'iso' => 'IL', 'iso3' => 'ISR', 'numcode' => '376', 'phonecode' => '972', 'currency' => ''),
            array('name' => 'ITALY', 'iso' => 'IT', 'iso3' => 'ITA', 'numcode' => '380', 'phonecode' => '39', 'currency' => ''),
            array('name' => 'JAMAICA', 'iso' => 'JM', 'iso3' => 'JAM', 'numcode' => '388', 'phonecode' => '1876', 'currency' => ''),
            array('name' => 'JAPAN', 'iso' => 'JP', 'iso3' => 'JPN', 'numcode' => '392', 'phonecode' => '81', 'currency' => ''),
            array('name' => 'JORDAN', 'iso' => 'JO', 'iso3' => 'JOR', 'numcode' => '400', 'phonecode' => '962', 'currency' => ''),
            array('name' => 'KAZAKHSTAN', 'iso' => 'KZ', 'iso3' => 'KAZ', 'numcode' => '398', 'phonecode' => '7', 'currency' => ''),
            array('name' => 'KENYA', 'iso' => 'KE', 'iso3' => 'KEN', 'numcode' => '404', 'phonecode' => '254', 'currency' => ''),
            array('name' => 'KIRIBATI', 'iso' => 'KI', 'iso3' => 'KIR', 'numcode' => '296', 'phonecode' => '686', 'currency' => ''),
            array('name' => 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF', 'iso' => 'KP', 'iso3' => 'PRK', 'numcode' => '408', 'phonecode' => '850', 'currency' => ''),
            array('name' => 'KOREA, REPUBLIC OF', 'iso' => 'KR', 'iso3' => 'KOR', 'numcode' => '410', 'phonecode' => '82', 'currency' => ''),
            array('name' => 'KUWAIT', 'iso' => 'KW', 'iso3' => 'KWT', 'numcode' => '414', 'phonecode' => '965', 'currency' => ''),
            array('name' => 'KYRGYZSTAN', 'iso' => 'KG', 'iso3' => 'KGZ', 'numcode' => '417', 'phonecode' => '996', 'currency' => ''),
            array('name' => 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC', 'iso' => 'LA', 'iso3' => 'LAO', 'numcode' => '418', 'phonecode' => '856', 'currency' => ''),
            array('name' => 'LATVIA', 'iso' => 'LV', 'iso3' => 'LVA', 'numcode' => '428', 'phonecode' => '371', 'currency' => ''),
            array('name' => 'LEBANON', 'iso' => 'LB', 'iso3' => 'LBN', 'numcode' => '422', 'phonecode' => '961', 'currency' => ''),
            array('name' => 'LESOTHO', 'iso' => 'LS', 'iso3' => 'LSO', 'numcode' => '426', 'phonecode' => '266', 'currency' => ''),
            array('name' => 'LIBERIA', 'iso' => 'LR', 'iso3' => 'LBR', 'numcode' => '430', 'phonecode' => '231', 'currency' => ''),
            array('name' => 'LIBYAN ARAB JAMAHIRIYA', 'iso' => 'LY', 'iso3' => 'LBY', 'numcode' => '434', 'phonecode' => '218', 'currency' => ''),
            array('name' => 'LIECHTENSTEIN', 'iso' => 'LI', 'iso3' => 'LIE', 'numcode' => '438', 'phonecode' => '423', 'currency' => ''),
            array('name' => 'LITHUANIA', 'iso' => 'LT', 'iso3' => 'LTU', 'numcode' => '440', 'phonecode' => '370', 'currency' => ''),
            array('name' => 'LUXEMBOURG', 'iso' => 'LU', 'iso3' => 'LUX', 'numcode' => '442', 'phonecode' => '352', 'currency' => ''),
            array('name' => 'MACAO', 'iso' => 'MO', 'iso3' => 'MAC', 'numcode' => '446', 'phonecode' => '853', 'currency' => ''),
            array('name' => 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'iso' => 'MK', 'iso3' => 'MKD', 'numcode' => '807', 'phonecode' => '389', 'currency' => ''),
            array('name' => 'MADAGASCAR', 'iso' => 'MG', 'iso3' => 'MDG', 'numcode' => '450', 'phonecode' => '261', 'currency' => ''),
            array('name' => 'MALAWI', 'iso' => 'MW', 'iso3' => 'MWI', 'numcode' => '454', 'phonecode' => '265', 'currency' => ''),
            array('name' => 'MALAYSIA', 'iso' => 'MY', 'iso3' => 'MYS', 'numcode' => '458', 'phonecode' => '60', 'currency' => ''),
            array('name' => 'MALDIVES', 'iso' => 'MV', 'iso3' => 'MDV', 'numcode' => '462', 'phonecode' => '960', 'currency' => ''),
            array('name' => 'MALI', 'iso' => 'ML', 'iso3' => 'MLI', 'numcode' => '466', 'phonecode' => '223', 'currency' => ''),
            array('name' => 'MALTA', 'iso' => 'MT', 'iso3' => 'MLT', 'numcode' => '470', 'phonecode' => '356', 'currency' => ''),
            array('name' => 'MARSHALL ISLANDS', 'iso' => 'MH', 'iso3' => 'MHL', 'numcode' => '584', 'phonecode' => '692', 'currency' => ''),
            array('name' => 'MARTINIQUE', 'iso' => 'MQ', 'iso3' => 'MTQ', 'numcode' => '474', 'phonecode' => '596', 'currency' => ''),
            array('name' => 'MAURITANIA', 'iso' => 'MR', 'iso3' => 'MRT', 'numcode' => '478', 'phonecode' => '222', 'currency' => ''),
            array('name' => 'MAURITIUS', 'iso' => 'MU', 'iso3' => 'MUS', 'numcode' => '480', 'phonecode' => '230', 'currency' => ''),
            array('name' => 'MAYOTTE', 'iso' => 'YT', 'iso3' => 'MYT', 'numcode' => '', 'phonecode' => '269', 'currency' => ''),
            array('name' => 'MEXICO', 'iso' => 'MX', 'iso3' => 'MEX', 'numcode' => '484', 'phonecode' => '52', 'currency' => ''),
            array('name' => 'MICRONESIA, FEDERATED STATES OF', 'iso' => 'FM', 'iso3' => 'FSM', 'numcode' => '583', 'phonecode' => '691', 'currency' => ''),
            array('name' => 'MOLDOVA, REPUBLIC OF', 'iso' => 'MD', 'iso3' => 'MDA', 'numcode' => '498', 'phonecode' => '373', 'currency' => ''),
            array('name' => 'MONACO', 'iso' => 'MC', 'iso3' => 'MCO', 'numcode' => '492', 'phonecode' => '377', 'currency' => ''),
            array('name' => 'MONGOLIA', 'iso' => 'MN', 'iso3' => 'MNG', 'numcode' => '496', 'phonecode' => '976', 'currency' => ''),
            array('name' => 'MONTSERRAT', 'iso' => 'MS', 'iso3' => 'MSR', 'numcode' => '500', 'phonecode' => '1664', 'currency' => ''),
            array('name' => 'MOROCCO', 'iso' => 'MA', 'iso3' => 'MAR', 'numcode' => '504', 'phonecode' => '212', 'currency' => ''),
            array('name' => 'MOZAMBIQUE', 'iso' => 'MZ', 'iso3' => 'MOZ', 'numcode' => '508', 'phonecode' => '258', 'currency' => ''),
            array('name' => 'MYANMAR', 'iso' => 'MM', 'iso3' => 'MMR', 'numcode' => '104', 'phonecode' => '95', 'currency' => ''),
            array('name' => 'NAMIBIA', 'iso' => 'NA', 'iso3' => 'NAM', 'numcode' => '516', 'phonecode' => '264', 'currency' => ''),
            array('name' => 'NAURU', 'iso' => 'NR', 'iso3' => 'NRU', 'numcode' => '520', 'phonecode' => '674', 'currency' => ''),
            array('name' => 'NEPAL', 'iso' => 'NP', 'iso3' => 'NPL', 'numcode' => '524', 'phonecode' => '977', 'currency' => ''),
            array('name' => 'NETHERLANDS', 'iso' => 'NL', 'iso3' => 'NLD', 'numcode' => '528', 'phonecode' => '31', 'currency' => ''),
            array('name' => 'NETHERLANDS ANTILLES', 'iso' => 'AN', 'iso3' => 'ANT', 'numcode' => '530', 'phonecode' => '599', 'currency' => ''),
            array('name' => 'NEW CALEDONIA', 'iso' => 'NC', 'iso3' => 'NCL', 'numcode' => '540', 'phonecode' => '687', 'currency' => ''),
            array('name' => 'NEW ZEALAND', 'iso' => 'NZ', 'iso3' => 'NZL', 'numcode' => '554', 'phonecode' => '64', 'currency' => ''),
            array('name' => 'NICARAGUA', 'iso' => 'NI', 'iso3' => 'NIC', 'numcode' => '558', 'phonecode' => '505', 'currency' => ''),
            array('name' => 'NIGER', 'iso' => 'NE', 'iso3' => 'NER', 'numcode' => '562', 'phonecode' => '227', 'currency' => ''),
            array('name' => 'NIGERIA', 'iso' => 'NG', 'iso3' => 'NGA', 'numcode' => '566', 'phonecode' => '234', 'currency' => ''),
            array('name' => 'NIUE', 'iso' => 'NU', 'iso3' => 'NIU', 'numcode' => '570', 'phonecode' => '683', 'currency' => ''),
            array('name' => 'NORFOLK ISLAND', 'iso' => 'NF', 'iso3' => 'NFK', 'numcode' => '574', 'phonecode' => '672', 'currency' => ''),
            array('name' => 'NORTHERN MARIANA ISLANDS', 'iso' => 'MP', 'iso3' => 'MNP', 'numcode' => '580', 'phonecode' => '1670', 'currency' => ''),
            array('name' => 'NORWAY', 'iso' => 'NO', 'iso3' => 'NOR', 'numcode' => '578', 'phonecode' => '47', 'currency' => ''),
            array('name' => 'OMAN', 'iso' => 'OM', 'iso3' => 'OMN', 'numcode' => '512', 'phonecode' => '968', 'currency' => ''),
            array('name' => 'PAKISTAN', 'iso' => 'PK', 'iso3' => 'PAK', 'numcode' => '586', 'phonecode' => '92', 'currency' => ''),
            array('name' => 'PALAU', 'iso' => 'PW', 'iso3' => 'PLW', 'numcode' => '585', 'phonecode' => '680', 'currency' => ''),
            array('name' => 'PALESTINIAN TERRITORY, OCCUPIED', 'iso' => 'PS', 'iso3' => 'PSE', 'numcode' => '275', 'phonecode' => '970', 'currency' => ''),
            array('name' => 'PANAMA', 'iso' => 'PA', 'iso3' => 'PAN', 'numcode' => '591', 'phonecode' => '507', 'currency' => ''),
            array('name' => 'PAPUA NEW GUINEA', 'iso' => 'PG', 'iso3' => 'PNG', 'numcode' => '598', 'phonecode' => '675', 'currency' => ''),
            array('name' => 'PARAGUAY', 'iso' => 'PY', 'iso3' => 'PRY', 'numcode' => '600', 'phonecode' => '595', 'currency' => ''),
            array('name' => 'PERU', 'iso' => 'PE', 'iso3' => 'PER', 'numcode' => '604', 'phonecode' => '51', 'currency' => ''),
            array('name' => 'PHILIPPINES', 'iso' => 'PH', 'iso3' => 'PHL', 'numcode' => '608', 'phonecode' => '63', 'currency' => ''),
            array('name' => 'PITCAIRN', 'iso' => 'PN', 'iso3' => 'PCN', 'numcode' => '612', 'phonecode' => '0', 'currency' => ''),
            array('name' => 'POLAND', 'iso' => 'PL', 'iso3' => 'POL', 'numcode' => '616', 'phonecode' => '48', 'currency' => ''),
            array('name' => 'PORTUGAL', 'iso' => 'PT', 'iso3' => 'PRT', 'numcode' => '620', 'phonecode' => '351', 'currency' => ''),
            array('name' => 'PUERTO RICO', 'iso' => 'PR', 'iso3' => 'PRI', 'numcode' => '630', 'phonecode' => '1787', 'currency' => ''),
            array('name' => 'QATAR', 'iso' => 'QA', 'iso3' => 'QAT', 'numcode' => '634', 'phonecode' => '974', 'currency' => ''),
            array('name' => 'REUNION', 'iso' => 'RE', 'iso3' => 'REU', 'numcode' => '638', 'phonecode' => '262', 'currency' => ''),
            array('name' => 'ROMANIA', 'iso' => 'RO', 'iso3' => 'ROM', 'numcode' => '642', 'phonecode' => '40', 'currency' => ''),
            array('name' => 'RUSSIAN FEDERATION', 'iso' => 'RU', 'iso3' => 'RUS', 'numcode' => '643', 'phonecode' => '70', 'currency' => ''),
            array('name' => 'RWANDA', 'iso' => 'RW', 'iso3' => 'RWA', 'numcode' => '646', 'phonecode' => '250', 'currency' => ''),
            array('name' => 'SAINT HELENA', 'iso' => 'SH', 'iso3' => 'SHN', 'numcode' => '654', 'phonecode' => '290', 'currency' => ''),
            array('name' => 'SAINT KITTS AND NEVIS', 'iso' => 'KN', 'iso3' => 'KNA', 'numcode' => '659', 'phonecode' => '1869', 'currency' => ''),
            array('name' => 'SAINT LUCIA', 'iso' => 'LC', 'iso3' => 'LCA', 'numcode' => '662', 'phonecode' => '1758', 'currency' => ''),
            array('name' => 'SAINT PIERRE AND MIQUELON', 'iso' => 'PM', 'iso3' => 'SPM', 'numcode' => '666', 'phonecode' => '508', 'currency' => ''),
            array('name' => 'SAINT VINCENT AND THE GRENADINES', 'iso' => 'VC', 'iso3' => 'VCT', 'numcode' => '670', 'phonecode' => '1784', 'currency' => ''),
            array('name' => 'SAMOA', 'iso' => 'WS', 'iso3' => 'WSM', 'numcode' => '882', 'phonecode' => '684', 'currency' => ''),
            array('name' => 'SAN MARINO', 'iso' => 'SM', 'iso3' => 'SMR', 'numcode' => '674', 'phonecode' => '378', 'currency' => ''),
            array('name' => 'SAO TOME AND PRINCIPE', 'iso' => 'ST', 'iso3' => 'STP', 'numcode' => '678', 'phonecode' => '239', 'currency' => ''),
            array('name' => 'SAUDI ARABIA', 'iso' => 'SA', 'iso3' => 'SAU', 'numcode' => '682', 'phonecode' => '966', 'currency' => ''),
            array('name' => 'SENEGAL', 'iso' => 'SN', 'iso3' => 'SEN', 'numcode' => '686', 'phonecode' => '221', 'currency' => ''),
            array('name' => 'SERBIA', 'iso' => 'RS', 'iso3' => 'SRB', 'numcode' => '', 'phonecode' => '381', 'currency' => ''),
            array('name' => 'SEYCHELLES', 'iso' => 'SC', 'iso3' => 'SYC', 'numcode' => '690', 'phonecode' => '248', 'currency' => ''),
            array('name' => 'SIERRA LEONE', 'iso' => 'SL', 'iso3' => 'SLE', 'numcode' => '694', 'phonecode' => '232', 'currency' => ''),
            array('name' => 'SINGAPORE', 'iso' => 'SG', 'iso3' => 'SGP', 'numcode' => '702', 'phonecode' => '65', 'currency' => ''),
            array('name' => 'SLOVAKIA', 'iso' => 'SK', 'iso3' => 'SVK', 'numcode' => '703', 'phonecode' => '421', 'currency' => ''),
            array('name' => 'SLOVENIA', 'iso' => 'SI', 'iso3' => 'SVN', 'numcode' => '705', 'phonecode' => '386', 'currency' => ''),
            array('name' => 'SOLOMON ISLANDS', 'iso' => 'SB', 'iso3' => 'SLB', 'numcode' => '90', 'phonecode' => '677', 'currency' => ''),
            array('name' => 'SOMALIA', 'iso' => 'SO', 'iso3' => 'SOM', 'numcode' => '706', 'phonecode' => '252', 'currency' => ''),
            array('name' => 'SOUTH AFRICA', 'iso' => 'ZA', 'iso3' => 'ZAF', 'numcode' => '710', 'phonecode' => '27', 'currency' => ''),
            array('name' => 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'iso' => 'GS', 'iso3' => 'SGS', 'numcode' => '', 'phonecode' => '0', 'currency' => ''),
            array('name' => 'SPAIN', 'iso' => 'ES', 'iso3' => 'ESP', 'numcode' => '724', 'phonecode' => '34', 'currency' => ''),
            array('name' => 'SRI LANKA', 'iso' => 'LK', 'iso3' => 'LKA', 'numcode' => '144', 'phonecode' => '94', 'currency' => ''),
            array('name' => 'SUDAN', 'iso' => 'SD', 'iso3' => 'SDN', 'numcode' => '736', 'phonecode' => '249', 'currency' => ''),
            array('name' => 'SURINAME', 'iso' => 'SR', 'iso3' => 'SUR', 'numcode' => '740', 'phonecode' => '597', 'currency' => ''),
            array('name' => 'SVALBARD AND JAN MAYEN', 'iso' => 'SJ', 'iso3' => 'SJM', 'numcode' => '744', 'phonecode' => '47', 'currency' => ''),
            array('name' => 'SWAZILAND', 'iso' => 'SZ', 'iso3' => 'SWZ', 'numcode' => '748', 'phonecode' => '268', 'currency' => ''),
            array('name' => 'SWEDEN', 'iso' => 'SE', 'iso3' => 'SWE', 'numcode' => '752', 'phonecode' => '46', 'currency' => ''),
            array('name' => 'SWITZERLAND', 'iso' => 'CH', 'iso3' => 'CHE', 'numcode' => '756', 'phonecode' => '41', 'currency' => ''),
            array('name' => 'SYRIAN ARAB REPUBLIC', 'iso' => 'SY', 'iso3' => 'SYR', 'numcode' => '760', 'phonecode' => '963', 'currency' => ''),
            array('name' => 'TAIWAN, PROVINCE OF CHINA', 'iso' => 'TW', 'iso3' => 'TWN', 'numcode' => '158', 'phonecode' => '886', 'currency' => ''),
            array('name' => 'TAJIKISTAN', 'iso' => 'TJ', 'iso3' => 'TJK', 'numcode' => '762', 'phonecode' => '992', 'currency' => ''),
            array('name' => 'TANZANIA, UNITED REPUBLIC OF', 'iso' => 'TZ', 'iso3' => 'TZA', 'numcode' => '834', 'phonecode' => '255', 'currency' => ''),
            array('name' => 'THAILAND', 'iso' => 'TH', 'iso3' => 'THA', 'numcode' => '764', 'phonecode' => '66', 'currency' => ''),
            array('name' => 'TIMOR-LESTE', 'iso' => 'TL', 'iso3' => 'TLS', 'numcode' => '', 'phonecode' => '670', 'currency' => ''),
            array('name' => 'TOGO', 'iso' => 'TG', 'iso3' => 'TGO', 'numcode' => '768', 'phonecode' => '228', 'currency' => ''),
            array('name' => 'TOKELAU', 'iso' => 'TK', 'iso3' => 'TKL', 'numcode' => '772', 'phonecode' => '690', 'currency' => ''),
            array('name' => 'TONGA', 'iso' => 'TO', 'iso3' => 'TON', 'numcode' => '776', 'phonecode' => '676', 'currency' => ''),
            array('name' => 'TRINIDAD AND TOBAGO', 'iso' => 'TT', 'iso3' => 'TTO', 'numcode' => '780', 'phonecode' => '1868', 'currency' => ''),
            array('name' => 'TUNISIA', 'iso' => 'TN', 'iso3' => 'TUN', 'numcode' => '788', 'phonecode' => '216', 'currency' => ''),
            array('name' => 'TURKEY', 'iso' => 'TR', 'iso3' => 'TUR', 'numcode' => '792', 'phonecode' => '90', 'currency' => ''),
            array('name' => 'TURKMENISTAN', 'iso' => 'TM', 'iso3' => 'TKM', 'numcode' => '795', 'phonecode' => '7370', 'currency' => ''),
            array('name' => 'TURKS AND CAICOS ISLANDS', 'iso' => 'TC', 'iso3' => 'TCA', 'numcode' => '796', 'phonecode' => '1649', 'currency' => ''),
            array('name' => 'TUVALU', 'iso' => 'TV', 'iso3' => 'TUV', 'numcode' => '798', 'phonecode' => '688', 'currency' => ''),
            array('name' => 'UGANDA', 'iso' => 'UG', 'iso3' => 'UGA', 'numcode' => '800', 'phonecode' => '256', 'currency' => ''),
            array('name' => 'UKRAINE', 'iso' => 'UA', 'iso3' => 'UKR', 'numcode' => '804', 'phonecode' => '380', 'currency' => ''),
            array('name' => 'UNITED ARAB EMIRATES', 'iso' => 'AE', 'iso3' => 'ARE', 'numcode' => '784', 'phonecode' => '971', 'currency' => ''),
            array('name' => 'UNITED KINGDOM', 'iso' => 'GB', 'iso3' => 'GBR', 'numcode' => '826', 'phonecode' => '44', 'currency' => ''),
            array('name' => 'UNITED STATES', 'iso' => 'US', 'iso3' => 'USA', 'numcode' => '840', 'phonecode' => '1', 'currency' => ''),
            array('name' => 'UNITED STATES MINOR OUTLYING ISLANDS', 'iso' => 'UM', 'iso3' => 'UMI', 'numcode' => '', 'phonecode' => '1', 'currency' => ''),
            array('name' => 'URUGUAY', 'iso' => 'UY', 'iso3' => 'URY', 'numcode' => '858', 'phonecode' => '598', 'currency' => ''),
            array('name' => 'UZBEKISTAN', 'iso' => 'UZ', 'iso3' => 'UZB', 'numcode' => '860', 'phonecode' => '998', 'currency' => ''),
            array('name' => 'VANUATU', 'iso' => 'VU', 'iso3' => 'VUT', 'numcode' => '548', 'phonecode' => '678', 'currency' => ''),
            array('name' => 'VENEZUELA', 'iso' => 'VE', 'iso3' => 'VEN', 'numcode' => '862', 'phonecode' => '58', 'currency' => ''),
            array('name' => 'VIET NAM', 'iso' => 'VN', 'iso3' => 'VNM', 'numcode' => '704', 'phonecode' => '84', 'currency' => ''),
            array('name' => 'VIRGIN ISLANDS, BRITISH', 'iso' => 'VG', 'iso3' => 'VGB', 'numcode' => '92', 'phonecode' => '1284', 'currency' => ''),
            array('name' => 'VIRGIN ISLANDS, U.S.', 'iso' => 'VI', 'iso3' => 'VIR', 'numcode' => '850', 'phonecode' => '1340', 'currency' => ''),
            array('name' => 'WALLIS AND FUTUNA', 'iso' => 'WF', 'iso3' => 'WLF', 'numcode' => '876', 'phonecode' => '681', 'currency' => ''),
            array('name' => 'WESTERN SAHARA', 'iso' => 'EH', 'iso3' => 'ESH', 'numcode' => '732', 'phonecode' => '212', 'currency' => ''),
            array('name' => 'YEMEN', 'iso' => 'YE', 'iso3' => 'YEM', 'numcode' => '887', 'phonecode' => '967', 'currency' => ''),
            array('name' => 'ZAMBIA', 'iso' => 'ZM', 'iso3' => 'ZMB', 'numcode' => '894', 'phonecode' => '260', 'currency' => ''),
            array('name' => 'ZIMBABWE', 'iso' => 'ZW', 'iso3' => 'ZWE', 'numcode' => '716', 'phonecode' => '263', 'currency' => ''),
        );

        DB::table('countries')->insert($countries);

    }
}